import Footer from "@/component/footer/footer";
import Header from "@/component/header/header";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      <body className="flex flex-shrink sm:min-h-full flex-col">
        <div className="flex flex-col min-h-screen"> 
          <Header />
          <main className="flex-grow sm:p-7"> 
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
